apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-test
  name: argo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-test
  template:
    metadata:
      labels:
        app: gitops-test
    spec:
      containers:
      - imge: nginx1.17
        name: argo-ctn



